# Changes here will be overwritten by Copier
_commit: v2.0.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: brantd@uw.edu
author_name: lincc-frameworks
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: dask_nested
project_license: MIT
project_name: dask-nested
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
